### ISSUE TITLE
Skip entire lines

### ISSUE THREAD

**Issue by joh-klein** [adaltas/node-csv-parse#215]
Is there a way to skip parsing entire lines if they contain a specific value? Or only parse them if they do contain a specific value?
I would have thought that this could be done with the "cast" option, but I was wrong.

Use case: I have a rather large csv where 1/3 of the lines are irrelevant information. To speed things up, I would like to skip all those lines (which are easily identifiable because they don't start with a specific keyword) and only parse the relevant lines - thus also saving time on cleaning up the result.

**Comment by wdavidw** [comment]
I am not sure you will gain much speed improvement. The parser will still need to loop through each character and if your line contains valid CSV, parser de CSV to ensure that when it is time to interpret valid line, it doesnt at the begining of a record (which isn't necessary the after a `record_delimiter` since it could be quoted). I'll be happy to be proved wrong and I dont have much time to benchmark it.
