### ISSUE TITLE
error when using cast function with colmuns true

### ISSUE THREAD

**Issue by mikiastilahun** [adaltas/node-csv-parse#233]
Error: Invalid Option columns: property "name" is required at position 0 when trying to use the cast option as a function with the columns set to true but works for cast set to true.

```js
parse(new Buffer(csv), {
    columns: true,
    cast: function(value, context) {
      if (context.column === "Verticals") {
        return value.splice(",").map(item => {
          if (item.trim() === "Artificial Intelligence & Machine Learning") {
            return "AI & ML";
          }
          return item.trim();
        });
      } else return context;
    }
  });```

**Comment by joh-klein** [comment]
It is rather difficult to understand what you are trying to do if you don't provide a small sample of the data you are trying to parse.
Maybe you already know this, but if you wrap your code like this:
![image](https://user-images.githubusercontent.com/3099832/54044903-68dfa100-41d0-11e9-959a-a87733011f8e.png)
it becomes a little easier to read:
```js
parse(new Buffer(csv), {
  columns: true,
  cast: function(value, context) {
    if (context.column === "Verticals") {
      return value.splice(",").map(item => {
        if (item.trim() === "Artificial Intelligence & Machine Learning") {
          return "AI & ML";
        }
        return item.trim();
      });
    } else return context;
  }
});
```
I found your issue, because mine is similar: #235

**Comment by mikiastilahun** [comment]
tnx for the suggesstions

**Comment by wdavidw** [comment]
Hi @mikiastilahun, `cast` must return valid columns value when casting the first line because the field present in the header are converted to a `columns` option. It is possible that #235 fix your issue. However, returning the `context` value like you did in your same is probably going to be treated as an invalid column value. You can look. at @mikiastilahun sample and how he is making use of the the `context.header` property. Could you get back to us if you have any question or close the issue otherwise, thank you.

**Comment by mikiastilahun** [comment]
thanks for the response
