### ISSUE TITLE
Option to parse column header from `from_line` instead of first line

### ISSUE THREAD

**Issue by zypA13510** [adaltas/node-csv-parse#263]
**Is your feature request related to a problem? Please describe.**
I have some csv files with some kind of title as the first few lines. Not sure this is conformant, but anyway, I need to parse these files.
It is frustrating that, even if I use `from_line: 4` to skip the first 3 lines, csv-parse `columns: true` still tries to detect column header from the first line, and the following error will be thrown:
> Error: Invalid Record Length: header length is 1, got 25 on line 4

**Describe the solution you'd like**
Maybe `from_line` can accept an object with a boolean `as_header` property?
Or a new number-type option `header_line` that defaults to 1 but can be changed to, e.g. 4?

**Describe alternatives you've considered**
For now, I have to manually specify an array as columns, then start from line 5.

**Additional context**
N/A

**Comment by wdavidw** [comment]
I consider having from_line not taking `header` into account to be more a bug than anything else. Thus, I don't believe we shall introduce any new property but instead just honor `header`. Also, since it is not a modification of the API but instead a correction, there would be no need to release a major version. Anyone would have objections?
