### ISSUE TITLE
csv-parse adds empty column that does not exist

### ISSUE THREAD

**Issue by Osolemio44** [adaltas/node-csv-parse#307]
Hi. i am parsing a csv text file and i get the error :
`Invalid Record Length: expect 13, got 12 on line 2`
after seraching a bit, i discovered that csv-parse detect a non existing column at the end. I checked the text file and there is no empty space or strange character at the end of the first line.

my text file sample:

```
FECHA HORA;ArcoLad II/C6H6 Flag;ArcoLad II/C6H5-CH3 Flag;ArcoLad II/C8H10 Flag;ArcoLad II/C6H5-CH2-CH3 Flag;ArcoLad II/O-XIL Flag;Renault1/BEN Flag;Renault1/TOL Flag;Renault1/XIL Flag;Renault4/BEN Flag;Renault4/TOL Flag;Renault4/XIL Flag;
01-01-2020 01:00;2,6 V;4,1 V;3,6 V;2 V;1,4 V;-9999 N;-9999 N;-9999 N;0,8 V;1 V;1,8 V
01-01-2020 02:00;3,2 V;4,5 V;4,7 V;2 V;0,6 V;-9999 N;-9999 N;-9999 N;0,9 V;0,9 V;0,8 V
01-01-2020 03:00;3,3 V;4 V;4,8 V;1,1 V;0,5 V;-9999 N;-9999 N;-9999 N;0,8 V;0,9 V;0,5 V
01-01-2020 04:00;2,7 V;4,2 V;5,2 V;1,3 V;1,2 V;-9999 N;-9999 N;-9999 N;0,8 V;1 V;0,4 V
01-01-2020 05:00;2,8 V;4 V;5,5 V;0,1 V;0,4 V;-9999 N;-9999 N;-9999 N;0,8 V;1 V;0,3 V
01-01-2020 06:00;2,4 V;4,1 V;5,3 V;0,1 V;0,1 V;-9999 N;-9999 N;-9999 N;0,7 V;1 V;0,4 V
```
My code:

```
const parse = require('csv-parse/lib/sync');
const fs = require('fs');

let fileData = fs.readFileSync(url, 'utf8');
        const records = parse(fileData, {
            delimiter: ";",
            skip_empty_lines: true,
            relaxColumnCount: true // <=== i added this option to bypass the error and check what is happening
        })
        console.log('records :>> ', records);
```
To discover what happens i enabled "relaxColumnCount". But i would prefer to know how to fix this behaviour than having to deal manually with 13 headers and 12 columns data.

![image](https://user-images.githubusercontent.com/55595063/106482600-e63fe900-64ad-11eb-9685-15811f91e614.png)

i made a small project to show you: https://stackblitz.com/edit/js-je3eyy?file=index.js

**Comment by wdavidw** [comment]
I have updated the label from bug to question because this is not a bug, it is by design. to my understanding, your CSV header is incorrect and there is not much we could do for such a corner case. However, I have a proposition for your case, return your own headers. The [`columns` option](https://csv.js.org/parse/options/columns/#as-a-function) can take the form of a function. It receives the first record as an argument, your header with 13 columns, and expect the final header columns, your expected 12 columns. In the function, you can just filter out the empty columns. Here is a working implementation:

```js
const records = parse(`
FECHA HORA;ArcoLad II/C6H6 Flag;ArcoLad II/C6H5-CH3 Flag;ArcoLad II/C8H10 Flag;ArcoLad II/C6H5-CH2-CH3 Flag;ArcoLad II/O-XIL Flag;Renault1/BEN Flag;Renault1/TOL Flag;Renault1/XIL Flag;Renault4/BEN Flag;Renault4/TOL Flag;Renault4/XIL Flag;
01-01-2020 01:00;2,6 V;4,1 V;3,6 V;2 V;1,4 V;-9999 N;-9999 N;-9999 N;0,8 V;1 V;1,8 V
01-01-2020 02:00;3,2 V;4,5 V;4,7 V;2 V;0,6 V;-9999 N;-9999 N;-9999 N;0,9 V;0,9 V;0,8 V
01-01-2020 03:00;3,3 V;4 V;4,8 V;1,1 V;0,5 V;-9999 N;-9999 N;-9999 N;0,8 V;0,9 V;0,5 V
01-01-2020 04:00;2,7 V;4,2 V;5,2 V;1,3 V;1,2 V;-9999 N;-9999 N;-9999 N;0,8 V;1 V;0,4 V
01-01-2020 05:00;2,8 V;4 V;5,5 V;0,1 V;0,4 V;-9999 N;-9999 N;-9999 N;0,8 V;1 V;0,3 V
01-01-2020 06:00;2,4 V;4,1 V;5,3 V;0,1 V;0,1 V;-9999 N;-9999 N;-9999 N;0,7 V;1 V;0,4 V
`, {
  columns: (headers) => {
    return headers.filter( header => header.length > 0)
  },
  delimiter: ";",
  skip_empty_lines: true,
})
console.log('records :>> ', records);
```

**Comment by Osolemio44** [comment]
thanks for your quick answer. Can you tell me why you think that csv headers are incorrect? i have been checking the file for like 2 hours and couldnt find a reason for this behaviour. what is wrong in the headers?

**Comment by wdavidw** [comment]
It is incorrect in the sense that it defines 13 fields in the header, even if the last one is empty, and 12 in the rest of the document.

If you wish to get arrays instead of objects, then you must remove the columns option. To get around the error in the header line, try setting the `from_line` option to `2`.
